vich_uploader:
    db_driver: orm
    
    metadata:
        type: attribute
    
    mappings:
        rooms:
            uri_prefix: /images/rooms
            upload_destination: '%kernel.project_dir%/public/images/rooms'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        users:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
        equipments:
            uri_prefix: /images/equipments
            upload_destination: '%kernel.project_dir%/public/images/equipments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
